# Generated by Django 3.1 on 2020-09-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
