# Generated by Django 3.1 on 2020-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='context',
            field=models.TextField(default=''),
        ),
    ]
