# Generated by Django 3.0.5 on 2020-08-02 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200802_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 12, 17, 51, 27419)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 12, 17, 51, 27419)),
        ),
    ]
