# Generated by Django 3.1 on 2020-08-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creation',
        ),
    ]
