# Generated by Django 3.1 on 2020-10-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='verb',
        ),
    ]
