# Generated by Django 3.0.5 on 2020-08-02 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200802_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 12, 30, 18, 389201)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 12, 30, 18, 389201)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 12, 30, 18, 388201)),
        ),
    ]
