# Generated by Django 3.1 on 2020-08-30 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_post_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
