# Generated by Django 3.0.8 on 2020-08-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
